##
## $Id: Makefile,v 1.40 2019/07/25 06:52:10 thor Exp $
##
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	meter dimension psnr pre diffimg suppress fftimg restrict thres compare maxfreq fftfilt \
		convertimg invert histogram colorhist scale crop mrse restore ycbcr xyz \
		mask stripe add peakpos mapping downsampler upsampler flip flipextend shift clamp \
		fill paste bayerconv debayer bayercolor whitebalance

DIRNAME	=	diff
SUPER	=	../

include	../Makefile.template
