##
## $Id: Makefile,v 1.47 2023/07/11 11:54:11 thor Exp $
##
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	meter dimension psnr pre diffimg suppress fftimg restrict thres compare maxfreq fftfilt \
		convertimg invert histogram colorhist scale crop mrse restore ycbcr xyz \
		mask stripe add peakpos mapping downsampler upsampler flip flipextend shift clamp \
		fill paste bayerconv debayer bayercolor tobayer whitebalance fromgrey sim2 butterfly \
		extractfield mergefields

DIRNAME	=	diff
SUPER	=	../

include	../Makefile.template
