##
## $Id: Makefile,v 1.35 2018/09/04 11:04:44 thor Exp $
##
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	meter dimension psnr pre diffimg fftimg restrict thres compare maxfreq fftfilt \
		convertimg invert histogram colorhist scale crop mrse restore ycbcr xyz \
		mask stripe add peakpos mapping downsampler upsampler flip shift clamp \
		fill paste bayerconv

DIRNAME	=	diff
SUPER	=	../

include	../Makefile.template
