##
## $Id: Makefile,v 1.2 2017/11/27 11:37:13 thor Exp $
##
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	types

DIRNAME	=	interface
SUPER	=	../

include	../Makefile.template
