##
## $Id: Makefile,v 1.3 2020/09/15 10:20:32 thor Exp $
##
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	types

DIRNAME	=	interface
SUPER	=	../

include	../Makefile.template
