##
## $Id: Makefile,v 1.4 2020/09/15 09:45:48 thor Exp $
##
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	main

XDIST	=	stripe.cpp

DIRNAME	=	cmd
SUPER	=	../

include	../Makefile.template
