##
## $Id: Makefile,v 1.5 2020/09/15 10:20:32 thor Exp $
##
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	main

XDIST	=	stripe.cpp

DIRNAME	=	cmd
SUPER	=	../

include	../Makefile.template
