##
## $Id: Makefile,v 1.4 2017/11/27 11:37:08 thor Exp $
##
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	main

XDIST	=	stripe.cpp

DIRNAME	=	cmd
SUPER	=	../

include	../Makefile.template
