##
## $Id: Makefile,v 1.2 2020/09/15 09:45:49 thor Exp $
##
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	stdlib stdio math stdarg setjmp \
		errno string ctype stddef unistd \
		assert

DIRNAME	=	std
SUPER	=	../

include	../Makefile.template
