##
## $Id: Makefile,v 1.4 2017/11/27 11:37:13 thor Exp $
##
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	fft file halffloat

DIRNAME	=	tools
SUPER	=	../

include	../Makefile.template
