##
## $Id: Makefile,v 1.4 2020/09/15 09:45:49 thor Exp $
##
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	fft file halffloat

DIRNAME	=	tools
SUPER	=	../

include	../Makefile.template
