##
## $Id: Makefile,v 1.5 2011-06-05 16:49:55 thor Exp $
##
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	tiffparser tiffwriter tifftags decoderbase decoderfunctions \
		trivialdecoder lzwdecoder packbitsdecoder

DIRNAME	=	tiff
SUPER	=	../

include	../Makefile.template
