##
## $Id: Makefile,v 1.7 2020/09/15 10:20:32 thor Exp $
##
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	tiffparser tiffwriter tifftags decoderbase decoderfunctions \
		trivialdecoder lzwdecoder packbitsdecoder

DIRNAME	=	tiff
SUPER	=	../

include	../Makefile.template
