##
## $Id: Makefile,v 1.9 2015/10/05 12:12:21 thor Exp $
##
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	imgspecs imglayout simplebmp simpleppm simplepgx \
		simpletiff simplergbe simplepng simpleexr \
		simpleraw simpledpx blankimg

DIRNAME	=	img
SUPER	=	../

include	../Makefile.template
